# General Jekyll Config
pygments: true
url: http://faresalaboud.me
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore]
host: 127.0.0.1
port: 9082
markdown: maruku

# Theme customization - please change from the defaults!
theme:
  # Color for top bar, links, etc
  highlight_color: '#49c583'

  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: fareskalaboud
    #bitbucket: philipj
    #hacker_news: swanson
    #stackexchange: 348619
    stackoverflow: 2188011
    twitter: FaresKAlaboud
    #facebook: faresalaboud
    #tumblr: animalygifs
    linkedin: faresalaboud
    gplus: 106188700391251912927

  # "Hi, I'm _______"
  name: Fares Alaboud
  email: hi@faresalaboud.me
  tagline: "A food-loving techie with a passion for programming."

  # google_analytics_key: UA-

  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: true
