# General Jekyll Config
pygments: true
url: http://faresalaboud.me
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore]
host: 127.0.0.1
port: 9082

# Theme customization - please change from the defaults!
theme:
  # Color for top bar, links, etc
  highlight_color: '#059de2'

  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: faresalaboud
    #bitbucket: philipj
    #hacker_news: swanson
    #stackexchange: 348619
    stackoverflow: 2188011
    twitter: FaresKAlaboud
    facebook: faresalaboud
    #tumblr: animalygifs
    linkedin: faresalaboud
    #gplus: 110552447039675960964

  # "Hi, I'm _______"
  name: Fares Alaboud
  email: hi@faresalaboud.me
  tagline: "A food-loving techie with a passion for programming."

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-xxxx-x

  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: true