name: Fares Alaboud's Personal Site
author: Fares Alaboud
markdown: redcarpet
pygments: true
baseurl: /
description: Personal Site & Portfolio
github: http://www.github.com/fareskalaboud
twitter: http://www.twitter.com/FaresKAlaboud
facebook: http://www.facebook.com/faresalaboud
linkedin: http://uk.linkedin.com/in/faresalaboud
email: hi@faresalaboud.me
location: 51°N   0°W
disqus: diqus-username

##Make sure to edit the above fields, especially for disqus. 

